sudo: false
language: node_js
cache:
  directories:
  - node_modules
node_js:
- '6'
deploy:
  api_key:
    secure: UhWqnW+HWPNyumG2rVQJ2HS7ZB1z6a9wr3oU7JaJddS+7p0fL141EurQ3ijNFW8vRLxVSuitvrzLv/wUeNMMMw5Tzg7Mi/j7uTZCD07Y9gEG/dMNc5woBFmOJOnsTfb/WnY+20bOlY96br0WAXPpagxXUf0TLpY9cdFmTGBW3qomzU7BLxElaXz+hmtmNe2g+G72hz7gWhRf1REEU2HHJuuULAobmVeWKKU9Epf68UOlq9D9GMxKgXBKRquH9H7l2ObMOLClHU4TpwATvEQ41ouiFGl9hF+8fuP0jMWIBFUbVWu4idRVO5Ww5fzZNGGAbsh/9oYfOa/t9vgOsW9c1yXqgx0jNbJobJLL9yDkeQRY8aG1hCYz7IOPEFVasc+fFyBjHtChnvZMqjXPrs8d/fHVcbSgTewlfteydZnXQSEURPoHmGJ2LyfMobPmnJfcQvSken1zKGXqdH8PjJUe4OJAFlTLFswXY5cOvmvMagAH1TuVeTj/r8QUJWfN6zuDU3O/NV0c9+SaBKlKGgB4ugnxvtwiZCm4ThYIxrcupWr3IVqDS02I79I9I95I7kQvEu8+uPUhG+7cLjyM5o6+KjqcSsaKhUFqymu7SA/U0IQFvZldRfpSGLr5GTrOXvvC91BMzzZxwF8lIObw8SB7efdbl5uxgvvZhZzo5/I848Y=
